/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package StalinSort

import spock.lang.Specification
import spock.lang.Unroll

class AppTest extends Specification {

    @Unroll
    def "execute staling sort"() {
        setup:
        def app = new App()

        expect:
        app.StalingSort(source) == result

        where:
        source             || result
        [0]                || [0]
        [0, 0]             || [0, 0]
        [0, 1]             || [0, 1]
        [0, 0, 1]          || [0, 0, 1]
        [0, 1, 1]          || [0, 1, 1]
        [0, 1, 2, 1]       || [0, 1, 2]
        // this pattern is display at readme.md
        // https://github.com/gustavo-depaula/stalin-sort
        [1, 2, 5, 3, 5, 7] || [1, 2, 5, 5, 7]

    }
}
